Create burger menu components
fe-feb23-code-hunters/fe_phone-catalog pull request #8
Opened 2023-06-08 20:03 UTC by Hamuud

[DEMO LINK](https://fe-feb23-code-hunters.github.io/fe_phone-catalog/)

2023-06-08 20:39 UTC, asmd564 commented
Use module styles (example: style.module.scss). in react (import style from './style.module.scss'

2023-06-08 20:40 UTC, asmd564 requested changes
Use module styles (example: style.module.scss). in react (import style from './style.module.scss'

2023-06-09 05:50 UTC, prokivskaaa commented on src/components/BurgerMenu/BurgerMenu.tsx
> +            <a href="/" className="logo">
Use tag Link

2023-06-09 05:52 UTC, prokivskaaa commented on src/components/BurgerMenu/BurgerMenu.scss
> +      height: 48px;
Lets declare local vars for height and padding

2023-06-09 05:55 UTC, prokivskaaa commented on src/App.tsx
> +    <BurgerMenu />
Deploy one more time as it is not present on GH-pages
<img width="409" alt="Знімок екрана 2023-06-09 о 08 55 49" src="https://github.com/fe-feb23-code-hunters/fe_phone-catalog/assets/107584278/562862cf-fde5-440c-82c0-805e4c6af526">

2023-06-09 05:56 UTC, prokivskaaa requested changes
Well done but pay attention to the comments

2023-06-09 12:15 UTC, prokivskaaa commented on src/index.tsx
> +  <BrowserRouter>
Use HashRouter instead

2023-06-09 12:25 UTC, prokivskaaa commented on src/components/BurgerMenu/BurgerMenu.module.scss
> +.burger__link {
![telegram-cloud-photo-size-2-5195406107730889569-x](https://github.com/fe-feb23-code-hunters/fe_phone-catalog/assets/107584278/9647f194-1a20-4570-ba1e-09341d8717e2)
Yulia learned how to implement bem to the module scss classes, here is an example of how to import them. Maybe we can use it somewhere in order to write less code?

2023-06-09 13:20 UTC, prokivskaaa approved these changes
Brilliant!

2023-06-09 14:36 UTC, asmd564 approved these changes

2023-06-09 14:43 UTC, prokivskaaa commented
Can you redeploy, please

2023-06-09 15:06 UTC, merged